export const initialFormKaryawan = {
  id_karyawan: "",
  nik: "",
  no_jkn: "",
  npp: "",
  nama: "",
  kota_lahir: "",
  tanggal_lahir: "",
  status_pernikahan: "",
  alamat_ktp: "",
  alamat_domisili: "",
  no_hp: "",
  nama_kontak_darurat: "",
  no_kontak_darurat: "",
  bank: "",
  nama_rekening: "",
  nomor_rekening: "",
  ukuran_baju: "",
  ukuran_celana: "",
  ukuran_sepatu: "",
  kategori_tenaga_kerja: "",
  jabatan: "",
  penempatan: "",
  basic_salary: 0,
  tunjangan_makan: 0,
  tunjangan_transport: 0,
  tunjangan_jabatan: 0,
  tmt: "",
  masa_kerja: 0,
  status_kerja: "",
  status_karyawan: "",
  tanggal_non_aktif: "",
  bpjs_kesehatan: "",
  bpjs_naker: "",
  keterangan: "",
  foto_url: "",
};

export type FormKaryawan = typeof initialFormKaryawan;
